### ISSUE TITLE
Full logout needed after admin promotion

### ISSUE THREAD

**Issue by jkennedyvz** [theparanoids/ashirt-server#247]
**Description of the problem including expected versus actual behavior**:
On account promotion to admin, the user can view the admin page, but there are errors for each of the views. The user must log out of ashirt and log back in to fix.
**Steps to reproduce**:
 and 

 1. Log in as non-admin user, and as admin user.
 2. Promote non-admin to admin
 3. Attempt to view admin settings as new admin

<img width="864" alt="Screen Shot 2021-02-04 at 4 22 56 PM" src="https://user-images.githubusercontent.com/65985482/106972893-a0ca2880-6706-11eb-8289-5d77506655f0.png">

**Provide logs (if relevant)**:

**Comment by JoelAtDeluxe** [comment]
This is known and expected behavior. A re-login is required on the backend, as permissions are tied to a user session. We can (and probably should) invalidate sessions when the user status changes. I think we do this when users get disabled, but maybe not when they're promoted, or demoted, from admin. If we do this, the user would _still_ need to login again, but they'd be forced into it, rather than requiring an explicit log out/log in cycle.

I can look for other solutions as well.

**Comment by JoelAtDeluxe** [comment]
So, the logic that logged someone out after a status change (either to admin or disabled) broke somewhere along the way. I'm looking into the best way to fix it now. Once it's done, it'll  behave as I noted earlier: a user will lose their session and be forced to log out. When they attempt to log back in, they'll have their new state (admin, disabled, or reversal to a normal user).
