### ISSUE TITLE
Role-based access

### ISSUE THREAD

**Issue by jkennedyvz** [theparanoids/ashirt-server#699]
Adding new teams to concluded operations is laborious at best. Simple group membership mapping for adjusting user permissions would make this much easier.

**Comment by legitimatecoder** [comment]
One concern is adding a team's worth of members to an op and then having that team gain and lose members over time.
Having an easy way to re-sync would be cool.
ie. add an "incident response" group to an operation  and separately control the membership of that group so that when a user is added to the group they automagically get visibility into all the "incident response" viewable operations.

**Comment by legitimatecoder** [comment]
If a user is both in an added group and individually added to an operation their permissions should be the most permissive setting.

**Comment by JoelAtDeluxe** [comment]
Who "owns" a group? How are they created and edited (I mean, obviously we'll need some new screens for this)? This feels like something that should live somewhere between an admin and a user, but we don't have that level of user in the application. Maybe this is more an admin feature, and admins get to decide how to manage these groups?

**Comment by legitimatecoder** [comment]
Yeah, this seems like an admin level task.  I don't think we're at the scale for needing a separate tier.
Created by selecting from the existing set of users and adding/removing them to a group.
